version: '3.1'
services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

    volumes:
      - /root/volume-redmine/redmine-postgres:/var/lib/postgresql

  redmine:
    build: ./
    image: redmine:latest
    restart: always
    depends_on:
      - postgresql
    environment:
      - TZ=America/Sao_Paulo

      - DB_ADAPTER=postgresql
      - DB_HOST=address
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=passwd
      - DB_NAME=redmine_db
      - DB_SSL_MODE=prefer

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=true
      - REDMINE_RELATIVE_URL_ROOT=
      - REDMINE_SECRET_TOKEN=

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=
      - REDMINE_BACKUP_EXPIRY=
      - REDMINE_BACKUP_TIME=

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=
      - SMTP_HOST=
      - SMTP_PORT=587
      - SMTP_USER=
      - SMTP_PASS=
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=
      - IMAP_PORT=993
      - IMAP_USER=
      - IMAP_PASS=
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

    ports:
      - "10083:80"
    volumes:
      - /root/volume-redmine/redmine:/home/redmine/data
      - /root/volume-redmine/redmine-logs:/var/log/redmine
